name: SAST Scan

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: List files
        run: ls -R

      - name: Run Bandit
        run: bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}"

      - name: Show Bandit version
        run: bandit --version
